version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cardb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - car-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: cardb
      DB_USER: user
      DB_PASSWORD: password
      DB_TYPE: mysql
      DB_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
    networks:
      - car-app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - car-app-network

volumes:
  mysql-data:

networks:
  car-app-network:
    driver: bridge
