"""Removed generic field, added price to car model

Revision ID: 45347bb406db
Revises: 
Create Date: 2025-09-16 09:08:02.868816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45347bb406db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.drop_column('generic_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generic_field', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('price')

    # ### end Alembic commands ###
