"""added body type to car

Revision ID: 4b590c6169ea
Revises: 3b9f53f9806c
Create Date: 2025-09-17 13:45:00.129535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b590c6169ea'
down_revision = '3b9f53f9806c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'body_types', ['body_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('body_type_id')

    # ### end Alembic commands ###
