"""changed column name from type to name in lookup tables

Revision ID: 8ddec3e2231f
Revises: 2199dd3861af
Create Date: 2025-09-18 18:04:30.501300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ddec3e2231f'
down_revision = '2199dd3861af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('type'))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('type')

    with op.batch_alter_table('drive_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=10), nullable=False))
        batch_op.drop_index(batch_op.f('type'))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('type')

    with op.batch_alter_table('engine_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('type'))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('type')

    with op.batch_alter_table('transmission_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('type'))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transmission_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('type'), ['type'], unique=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('engine_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('type'), ['type'], unique=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('drive_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('type'), ['type'], unique=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('body_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('type'), ['type'], unique=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
